name: Continuous Integration

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - run: nix --version
      - name: Format
        run: nix --accept-flake-config fmt -- --fail-on-change
      - name: Build 
        run: nix --accept-flake-config build -j auto